export const GET_ALL_RESTAURANTS_REQUEST = "GET_ALL_RESTAURANTS_REQUEST";

export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";

export const GET_ALL_RESTAURANTS_FAIL = "GET_ALL_RESTAURANTS_FAIL";

export const GET_SINGLE_RESTAURANT_REQUEST = "GET_SINGLE_RESTAURANT_REQUEST";

export const GET_SINGLE_RESTAURANT_SUCCESS = "GET_SINGLE_RESTAURANT_SUCCESS";

export const GET_SINGLE_RESTAURANT_FAIL = "GET_SINGLE_RESTAURANT_FAIL";

export const GET_FIRST_RESTAURANT_DATA = "GET_FIRST_RESTAURANT_DATA";

export const SUBMIT_FEEDBACK_REQUEST = "SUBMIT_FEEDBACK_REQUEST";
export const SUBMIT_FEEDBACK_SUCCESS = "SUBMIT_FEEDBACK_SUCCESS";
export const SUBMIT_FEEDBACK_FAIL = "SUBMIT_FEEDBACK_FAIL";

export const RATE = "RATE";
